spring:
  application:
    name: admin
  datasource:
    url: jdbc:postgresql://localhost:5432/diplom
    username: mihail
    password: postgres
  main:
    lazy-initialization: true
  jpa:
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf

dropbox:
  access:
    token: ${ACCESS_TOKEN}
logging:
  file:
    name: public.log
  level:
    root: info

server:
  port: 8080
