spring:
  application:
    name: admin
  datasource:
    username: postgres
    password: postgres
    url:  jdbc:postgresql://localhost:5432/poland
  main:
    lazy-initialization: true
  jpa:
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  thymeleaf:
    servlet:
      content-type: text/html
    suffix: .html
    cache: false
jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf

logging:
  file:
    name: public.log
  level:
    root: info

server:
  port: 8080

path_to_file: //свойпуть
