spring:
  application:
    name: producer
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/poland
  main:
    lazy-initialization: true
  jpa:
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 9090