spring:
  application:
    name: clients
  datasource:
    username: ${USER}
    password: ${PASSWORD}
    url: ${URI}
  main:
    lazy-initialization: true
  jpa:
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    topic-product:
      name: product-topic

server:
  port: 8081